FROM alpine:3.22.0
RUN apk update && apk add nginx
# RUN adduser -D -g 'www' www
# RUN mkdir /www \
#   chown -R www:www /var/lib/nginx\
#   chown -R www:www /www

COPY default.conf /etc/nginx/http.d/default.conf
RUN cat /etc/nginx/http.d/default.conf
RUN mkdir -p /run/nginx

CMD ["nginx", "-g", "daemon off; pid /tmp/nginx.pid;"]
